version: "3"
services:
  flask:
    build: ./flask
    image: flask:latest
    depends_on: 
      - redis
    ports:
      - "80:80"
    networks: 
      - flask
    volumes: 
      - /home/roguecomp/github/docker/app/flask/flask.py:/flask.py
    entrypoint: [ "pypy", "flask.py" ] 
    restart: unless-stopped
  redis:
    image: redis:alpine
    expose: 
    - "6379"
    networks: 
      - flask
    restart: unless-stopped
networks: 
  flask:
    driver: bridge
    enable_ipv6: false



