version: "3"

services:
  fetch:
    build: ./fetch
    image: fetch:latest
    container_name: fetch
    depends_on: 
      - redis
    networks: 
      - fetch
    restart: unless-stopped

  flask:
    build: ./flask
    image: flask:latest
    container_name: flask
    depends_on: 
      - redis
    ports:
      - "80:80"
    networks: 
      - flask
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    expose: 
    - "6379"
    networks: 
      - flask
      - fetch
    restart: unless-stopped

networks: 
  flask:
    driver: bridge
    enable_ipv6: false
  fetch:
    driver: bridge
    enable_ipv6: false




