version: "3"

services:
        server:
                build:
                        ./server-node
                image: ubuntu-dds-node:latest
                deploy:
                        resources:
                                limits:
                                        cpus: '0.50'
                                        memory: 150M
                                reservations:
                                        memory: 100M
                        replicas: 10
                expose:
                        - "22"
                volumes:
                        - ./src:/home/src
                command: tail -f /dev/null
                restart: unless-stopped
        master:
                build:
                        ./ansible
                container_name: master-dds-node
                image: master-dds-node:latest
                volumes:
                        - ./src:/home/src
                command: tail -f /dev/null
                restart: unless-stopped
