version: "3"

services:
        server:
                build:
                        ./slave
                image: ubuntu-ansible:latest
                deploy:
                        replicas: 10
                expose:
                        - "22"
                volumes:
                        - ./src:/home/src
                command: tail -f /dev/null
                restart: unless-stopped
        master:
                build:
                        ./ansible
                container_name: ansible
                image: ansible-practise:latest
                volumes:
                        - ./src:/home/src
                command: tail -f /dev/null
                restart: unless-stopped
