version: "3.9"

services: 
    redis:
      image: redis:alpine
      container_name: redis
      hostname: redis
      expose: 
        - "6379"
      networks: 
        - app
      restart: unless-stopped

    selenium:
      build: ./selenium
      image: pypy:messenger
      container_name: selenium
      environment:
        PYTHONUNBUFFERED: 1
      networks: 
        - app
      depends_on:
        - "redis"
      restart: unless-stopped
    
    
networks: 
  app:
    driver: bridge
    enable_ipv6: false
    name: app
